# Generated by Django 4.1.7 on 2023-03-31 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shrinkbot', '0008_chat_delete_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='username',
        ),
    ]
