# Generated by Django 4.1.7 on 2023-03-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shrinkbot', '0006_queries_chats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chats',
            old_name='user',
            new_name='username',
        ),
    ]
